# Generated by Django 5.2.4 on 2026-06-30 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kodi')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Joylashuvi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Stantsiya',
                'verbose_name_plural': 'Stantsiyalar',
                'db_table': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_column='Event_date', verbose_name='Sana')),
                ('event_time', models.TimeField(blank=True, db_column='Event_time', null=True, verbose_name='Vaqt')),
                ('latitude', models.FloatField(db_column='Latitude', verbose_name='Kenglik')),
                ('longitude', models.FloatField(db_column='Longitude', verbose_name='Uzunlik')),
                ('depth', models.FloatField(blank=True, db_column='Depth', null=True, verbose_name='Chuqurlik (km)')),
                ('mb', models.FloatField(blank=True, db_column='Mb', null=True, verbose_name='Magnituda (Mb)')),
                ('epicenter', models.CharField(blank=True, db_column='Epicenter', max_length=150, null=True, verbose_name='Epitsentr')),
            ],
            options={
                'verbose_name': 'Zilzila',
                'verbose_name_plural': 'Zilzilalar katalogi',
                'db_table': 'catalog',
                'ordering': ['-event_date', '-event_time'],
                'indexes': [models.Index(fields=['event_date'], name='idx_catalog_event_date'), models.Index(fields=['mb'], name='idx_catalog_mb')],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name="O'lchov vaqti")),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Qiymat')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Yaroqli')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='app_magnitka.station', verbose_name='Stantsiya')),
            ],
            options={
                'verbose_name': "O'lchov",
                'verbose_name_plural': "O'lchovlar",
                'db_table': 'measurements',
                'indexes': [models.Index(fields=['measured_at'], name='idx_measured_at'), models.Index(fields=['station', 'measured_at'], name='idx_station_time')],
                'unique_together': {('station', 'measured_at')},
            },
        ),
    ]
