# Generated by Django 5.2.4 on 2026-06-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_magnitka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='is_valid',
        ),
    ]
