# Generated by Django 5.2.4 on 2026-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skvajina', models.CharField(db_index=True, max_length=255, verbose_name='Skvajina nomi')),
                ('parameter', models.CharField(db_index=True, max_length=100, verbose_name='Parameter (CH4, He, O2, etc.)')),
                ('time_period_months', models.IntegerField(choices=[(1, '1 oy'), (3, '3 oy'), (6, '6 oy'), (12, '12 oy'), (24, '24 oy')], verbose_name="Vaqt oralig'i (oylar)")),
                ('anomaly_duration_days', models.IntegerField(choices=[(3, '3 kun'), (5, '5 kun'), (7, '7 kun'), (10, '10 kun'), (14, '14 kun'), (30, '30 kun'), (60, '60 kun')], verbose_name='Anomaliya davomiyligi (kunlar)')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Magnitude (optional)')),
                ('detected_anomalies_count', models.IntegerField(default=0, verbose_name='Aniqlangan anomaliyalar soni')),
                ('anomaly_start_date', models.DateField(blank=True, null=True, verbose_name='Anomaliya boshlangan sana')),
                ('anomaly_end_date', models.DateField(blank=True, null=True, verbose_name='Anomaliya tugagan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session ID')),
            ],
            options={
                'verbose_name': 'Anomaliya Kayit',
                'verbose_name_plural': 'Anomaliya Kayitlari',
                'db_table': 'app_anomaly_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skvajina', 'parameter'], name='app_anomaly_skvajin_d95170_idx'), models.Index(fields=['created_at'], name='app_anomaly_created_068d8b_idx'), models.Index(fields=['is_active'], name='app_anomaly_is_acti_ccaac9_idx')],
            },
        ),
    ]
