# Generated by Django 5.2.4 on 2026-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anomaly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyrecord',
            name='days_back',
            field=models.IntegerField(blank=True, help_text='Nechi kun orqagadan analiz qilindi', null=True),
        ),
    ]
