# Generated by Django 5.2.4 on 2026-02-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anomaly', '0002_anomalyrecord_days_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalyrecord',
            name='days_back',
        ),
        migrations.AddField(
            model_name='anomalyrecord',
            name='recent_days_filter',
            field=models.IntegerField(default=7, verbose_name='Oxirgi necha kunlik anomaliyalar filtrlanadi'),
        ),
    ]
