# Generated by Django 5.2.4 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anomaly', '0003_remove_anomalyrecord_days_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyrecord',
            name='anomaly_duration_days',
            field=models.IntegerField(
                choices=[
                    (1, '1 kun'),
                    (3, '3 kun'),
                    (5, '5 kun'),
                    (7, '7 kun'),
                    (10, '10 kun'),
                    (14, '14 kun'),
                    (30, '30 kun'),
                    (60, '60 kun'),
                ],
                verbose_name='Anomaliya davomiyligi (kunlar)',
            ),
        ),
    ]
