# Generated by Django 5.2.4 on 2025-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllIzmereniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stansiya', models.CharField(max_length=100)),
                ('skvajina', models.CharField(max_length=100)),
                ('izmereniya', models.CharField(max_length=100)),
                ('ssid_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'all_izmereniya',
            },
        ),
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('quduq_turi', models.CharField(blank=True, max_length=50, null=True)),
                ('suv_qatlami', models.CharField(blank=True, max_length=50, null=True)),
                ('chuqurlik', models.IntegerField(blank=True, null=True)),
                ('seysmotektonik_holat', models.TextField(blank=True, null=True)),
                ('strategrafik_taqsimoti', models.CharField(blank=True, max_length=50, null=True)),
                ('litologik_tarkibi', models.TextField(blank=True, null=True)),
                ('mineralizatsiya', models.ImageField(blank=True, null=True, upload_to='mineralizatsiya/')),
            ],
            options={
                'db_table': 'malumot',
            },
        ),
        migrations.CreateModel(
            name='Skvajina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naim', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
            options={
                'db_table': 'skvajina',
            },
        ),
    ]
