# Generated by Django 5.2.4 on 2025-11-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malumot',
            name='chuqurlik',
        ),
        migrations.RemoveField(
            model_name='malumot',
            name='litologik_tarkibi',
        ),
        migrations.RemoveField(
            model_name='malumot',
            name='quduq_turi',
        ),
        migrations.RemoveField(
            model_name='malumot',
            name='seysmotektonik_holat',
        ),
        migrations.RemoveField(
            model_name='malumot',
            name='strategrafik_taqsimoti',
        ),
        migrations.RemoveField(
            model_name='malumot',
            name='suv_qatlami',
        ),
        migrations.AlterModelTable(
            name='malumot',
            table=None,
        ),
    ]
