# Generated by Django 5.2.4 on 2025-11-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0002_remove_malumot_chuqurlik_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='malumot',
            table='malumot',
        ),
    ]
