# Generated by Django 5.2.4 on 2025-12-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0003_alter_malumot_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='malumot',
            table='malumot1',
        ),
    ]
