# Generated by Django 5.2.4 on 2026-01-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0004_alter_malumot_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allizmereniya',
            name='skvajina',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='allizmereniya',
            name='ssid_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='allizmereniya',
            name='stansiya',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skvajina',
            name='naim',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='allizmereniya',
            index=models.Index(fields=['stansiya', 'skvajina'], name='idx_station_well'),
        ),
        migrations.AddIndex(
            model_name='allizmereniya',
            index=models.Index(fields=['ssid_id'], name='idx_ssid'),
        ),
        migrations.AddIndex(
            model_name='skvajina',
            index=models.Index(fields=['naim'], name='idx_skvajina_name'),
        ),
        migrations.AddIndex(
            model_name='skvajina',
            index=models.Index(fields=['Latitude', 'Longitude'], name='idx_skvajina_coords'),
        ),
    ]
