# Generated by Django 5.2.4 on 2026-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0005_alter_allizmereniya_skvajina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malumot',
            name='nomi',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='malumot',
            index=models.Index(fields=['nomi'], name='idx_malumot_nomi'),
        ),
    ]
