# Generated by Django 5.2.4 on 2026-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0006_alter_malumot_nomi_malumot_idx_malumot_nomi'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allizmereniya',
            name='idx_ssid',
        ),
        migrations.RenameField(
            model_name='allizmereniya',
            old_name='ssid_id',
            new_name='ssdi_id',
        ),
        migrations.AddIndex(
            model_name='allizmereniya',
            index=models.Index(fields=['ssdi_id'], name='idx_ssid'),
        ),
    ]
