# Generated by Django 5.2.4 on 2026-01-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seismos_app', '0007_remove_allizmereniya_idx_ssid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allizmereniya',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='malumot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skvajina',
            options={'managed': False},
        ),
    ]
