# Generated by Django 5.2.4 on 2025-12-12 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login vaqti')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name="Brauzer ma'lumoti")),
                ('success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Login tarixi',
                'verbose_name_plural': 'Login tarixi',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='app_users_l_login_t_e0f247_idx'), models.Index(fields=['user', '-login_time'], name='app_users_l_user_id_d90c80_idx')],
            },
        ),
    ]
