# Generated by Django 5.2.4 on 2025-09-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date', models.DateField()),
                ('Event_time', models.TimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Depth', models.FloatField()),
                ('Mb', models.FloatField()),
                ('Epicenter', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
    ]
