# Generated by Django 5.2.4 on 2026-01-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': False, 'ordering': ['-Event_date', '-Event_time']},
        ),
    ]
