# Generated by Django 5.2.4 on 2025-09-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydrogenSeismology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(blank=True, max_length=255, null=True)),
                ('well_code', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('he', models.FloatField(blank=True, null=True)),
                ('h2', models.FloatField(blank=True, null=True)),
                ('o2', models.FloatField(blank=True, null=True)),
                ('n2', models.FloatField(blank=True, null=True)),
                ('ch4', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('c2h6', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('eh', models.FloatField(blank=True, null=True)),
                ('hco3', models.FloatField(blank=True, null=True)),
                ('ci2', models.FloatField(blank=True, null=True)),
                ('sio2', models.FloatField(blank=True, null=True)),
                ('f', models.FloatField(blank=True, null=True)),
                ('i', models.FloatField(blank=True, null=True)),
                ('b2o3', models.FloatField(blank=True, null=True)),
                ('dis_rn', models.FloatField(blank=True, null=True)),
                ('nep_rn', models.FloatField(blank=True, null=True)),
                ('he2', models.FloatField(blank=True, null=True)),
                ('t0', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('p', models.FloatField(blank=True, null=True)),
                ('eocc', models.FloatField(blank=True, null=True)),
                ('nep_t0', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hydrogen_seismologies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_code', models.CharField(help_text="API'dagi stansiya kodi (masalan, 'SMRM')", max_length=50, unique=True)),
                ('db_name', models.CharField(help_text="Bazada saqlanadigan to'liq nomi (masalan, 'Namangan KPS')", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(help_text="API'dagi quduq nomi (masalan, 'Jumabozo'r 1')", max_length=255)),
                ('db_name', models.CharField(help_text="Bazad a saqlanadigan quduq nomi (masalan, 'Jumabozor 1')", max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='download_base_app.station')),
            ],
        ),
    ]
