# Generated by Django 5.2.4 on 2026-01-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['api_code'], name='idx_station_api'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['db_name'], name='idx_station_db'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['station', 'api_name'], name='idx_well_station_api'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['station', 'db_name'], name='idx_well_station_db'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['api_name'], name='idx_well_api'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['db_name'], name='idx_well_db'),
        ),
    ]
